services:
  elasticsearch:
    image: elasticsearch:8.15.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=node-1
      - network.host=0.0.0.0
      - http.port=9200
      - logger.level=warn
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.high=99%
      - cluster.routing.allocation.disk.watermark.low=99%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./volumes/elasticsearch/:/usr/share/elasticsearch/data
